### PR TITLE
Update AWS configuration relating to the AWS SDK v2 changes

### PR DESCRIPTION
**Pull request by jdimeo**
See https://github.com/tolgee/tolgee-platform/issues/1271

### CODE REVIEW

**Comment by JanCizmar** [comment]
@Martin005, since we are generating the docs now, I am not sure, how do we want proceed with this.

**Comment by Martin005** [comment]
@JanCizmar
I think I will first need to adjust the PR [in platform](https://github.com/tolgee/tolgee-platform/pull/1734) as it contains a conflict with the updates to [AwsMachineTranslationProperties.kt](https://github.com/tolgee/tolgee-platform/pull/1614/files#diff-39f02320194376d438dc4fa965ee414138adab04ff2d39644fa542e4435e8bfa).
Then I will update the PR [here in documentation](https://github.com/tolgee/documentation/pull/417) with the adjustments and we can close this PR as the changes will be made in the other [PR in documentation](https://github.com/tolgee/documentation/pull/417).
Do you agree?

**Comment by jdimeo** [comment]
I'm not following but a) I think it's great that the docs are being generated and b) I didn't include the S3 docs too, mentioning that access key and secret are no longer required (I only updated the AWS translate docs here)

**Comment by JanCizmar** [comment]
@Martin005 I agree

**Comment by Martin005** [comment]
Changes moved to https://github.com/tolgee/documentation/pull/417 🙂

**Pull request closed without merging**
