### PR TITLE
 feat: Tolgee Platform v3, Tolgee JS v5, versioned docs

### PR DESCRIPTION
**Pull request by JanCizmar**
I did this:
- Added versioning for both Tolgee platform and Tolgee JS
- Moved the new Tolgee JS SDK docs into `js-sdk` docs plugin dir.

### CODE REVIEW

**Comment by stepan662** [comment]
The version selector is not very intuitive:

Snímek obrazovky 2022-11-21 v 18 45 27

**Comment by JanCizmar** [comment]
> The version selector is not very intuitive:
Why do you think so?

**Comment by cyyynthia** [comment]
I think the version selector needs to be distinguished from docs categories. As-is it feels like a classic documentation section which may contain changelog info, rather than a selector.

With a version selector now in the navbar, I think the version element in the sidebar can be dropped

**Comment by stepan662** [comment]
Looks good :)

**Review by stepan662 — APPROVED** [review]

**Pull request merged**
