### PR TITLE
Fixed config typo

### PR DESCRIPTION
**Pull request by rex2630**

### CODE REVIEW

**Comment by JanCizmar** [comment]
Hey. It's not a typo. There is a difference between "_", and "-". It is recommended to use "-" character in the property names. The "." in env can be replaced with "_". Anyway, Spring accepts also "_" instead of "-" character, so your approach also works, but it might be confusing. I'll update the page to provide a proper configuration via configuration yaml.

**Comment by JanCizmar** [comment]
https://github.com/tolgee/documentation/issues/337

**Comment by JanCizmar** [comment]
It's fixed in the docs now. So you can follow the approach with configuration file. https://github.com/tolgee/documentation/commit/27369fd2d0328dcea71c06223b548a213bba8c50

**Comment by rex2630** [comment]
Thank you :)

Dne po 9. 1. 2023 18:51 uživatel Jan Cizmar ***@***.***>
napsal:

**Pull request closed without merging**
