### PR TITLE
fix: update docs for https://github.com/tolgee/tolgee-cli/pull/37

### PR DESCRIPTION
**Pull request by ecstrema**
Also clarify where to find the project ID.

### CODE REVIEW

**Comment by JanCizmar** [comment]
Hey! Thanks for the fix! 🥇

**Comment by JanCizmar** [comment]
Oh! I see, you mean it can be string containing number. In that case I would specify it, since it might be confused with slug, which we currently don't have imlemented.

**Comment by ecstrema** [comment]
Is this better?

**Review by JanCizmar — APPROVED** [review]

**Comment by JanCizmar** [comment]
Great!

**Pull request merged**
