### PR TITLE
fix: Solve duplicate `/api/export` reference

### PR DESCRIPTION
**Pull request by StaNov**
Both `export.api.mdx` and `export.tag.mdx` have the same colliding URL. This commit moves `export.api.mdx` to `/api/export-data` and makes the `/api/export` the proper parent page.

### CODE REVIEW

**Comment by JanCizmar** [comment]
These files are generated.

**Comment by StaNov** [comment]
Properly fixed in tolgee/tolgee-platform#2704.

**Comment by StaNov** [comment]
Or maybe merge this one as well to fix the slug conflict until new docs from platform are generated.

@stepan662, what do you think?

**Comment by stepan662** [comment]
It's telling me that the branch was deleted and the PR can't be reopened. Maybe try to re-create the branch or create a new PR

**Comment by StaNov** [comment]
Done.

**Review by stepan662 — APPROVED** [review]

**Pull request merged**
